<?php 

$config['upload_params'] = array(
	'allowed_types' => 'gif|jpg|png|jpeg',
	'max_size' => '5000',
	'remove_spaces' => true,
	'encrypt_name' => true,
	'upload_path' => BASEPATH.'../upload/admin/ueditor/',	//上传路径
	'pic_path'=>'/upload/admin/ueditor/'	//用于显示的图片路径
);

//编辑器文件上传配置
$config['ueditor_config'] =array(
    'imageActionName' => 'uploadimage',
    'imageFieldName' => 'upfile',
    'imageMaxSize' => 2048000,
    'imageAllowFiles' =>
        array (
            0 => '.png',
            1 => '.jpg',
            2 => '.jpeg',
            3 => '.gif',
            4 => '.bmp',
        ),
    'imageCompressEnable' => true,
    'imageCompressBorder' => 1600,
    'imageInsertAlign' => 'none',
    'imageUrlPrefix' => '',
    'imagePathFormat' => '/image/{yyyy}{mm}{dd}/',
    'scrawlActionName' => 'uploadscrawl',
    'scrawlFieldName' => 'upfile',
    'scrawlPathFormat' => '/image/{yyyy}{mm}{dd}/',
    'scrawlMaxSize' => 2048000,
    'scrawlUrlPrefix' => '',
    'scrawlInsertAlign' => 'none',
    'snapscreenActionName' => 'uploadimage',
    'snapscreenPathFormat' => '/image/{yyyy}{mm}{dd}/',
    'snapscreenUrlPrefix' => '',
    'snapscreenInsertAlign' => 'none',
    'catcherLocalDomain' =>
        array (
            0 => '127.0.0.1',
            1 => 'localhost',
            2 => 'img.baidu.com',
        ),
    'catcherActionName' => 'catchimage',
    'catcherFieldName' => 'source',
    'catcherPathFormat' => '/image/{yyyy}{mm}{dd}/',
    'catcherUrlPrefix' => '',
    'catcherMaxSize' => 2048000,
    'catcherAllowFiles' =>
        array (
            0 => '.png',
            1 => '.jpg',
            2 => '.jpeg',
            3 => '.gif',
            4 => '.bmp',
        ),
    'videoActionName' => 'uploadvideo',
    'videoFieldName' => 'upfile',
    'videoPathFormat' => '/video/{yyyy}{mm}{dd}/',
    'videoUrlPrefix' => '',
    'videoMaxSize' => 102400000,
    'videoAllowFiles' =>
        array (
            0 => '.flv',
            1 => '.swf',
            2 => '.mkv',
            3 => '.avi',
            4 => '.rm',
            5 => '.rmvb',
            6 => '.mpeg',
            7 => '.mpg',
            8 => '.ogg',
            9 => '.ogv',
            10 => '.mov',
            11 => '.wmv',
            12 => '.mp4',
            13 => '.webm',
            14 => '.mp3',
            15 => '.wav',
            16 => '.mid',
        ),
    'fileActionName' => 'uploadfile',
    'fileFieldName' => 'upfile',
    'filePathFormat' => '/file/{yyyy}{mm}{dd}/',
    'fileUrlPrefix' => '',
    'fileMaxSize' => 20480000,
    'fileAllowFiles' =>
        array (
            0 => '.png',
            1 => '.jpg',
            2 => '.jpeg',
            3 => '.gif',
            4 => '.bmp',
            5 => '.flv',
            6 => '.swf',
            7 => '.mkv',
            8 => '.avi',
            9 => '.rm',
            10 => '.rmvb',
            11 => '.mpeg',
            12 => '.mpg',
            13 => '.ogg',
            14 => '.ogv',
            15 => '.mov',
            16 => '.wmv',
            17 => '.mp4',
            18 => '.webm',
            19 => '.mp3',
            20 => '.wav',
            21 => '.mid',
            22 => '.rar',
            23 => '.zip',
            24 => '.tar',
            25 => '.gz',
            26 => '.7z',
            27 => '.bz2',
            28 => '.cab',
            29 => '.iso',
            30 => '.doc',
            31 => '.docx',
            32 => '.xls',
            33 => '.xlsx',
            34 => '.ppt',
            35 => '.pptx',
            36 => '.pdf',
            37 => '.txt',
            38 => '.md',
            39 => '.xml',
        ),
    'imageManagerActionName' => 'listimage',
    'imageManagerListPath' => '/image/',
    'imageManagerListSize' => 20,
    'imageManagerUrlPrefix' => '',
    'imageManagerInsertAlign' => 'none',
    'imageManagerAllowFiles' =>
        array (
            0 => '.png',
            1 => '.jpg',
            2 => '.jpeg',
            3 => '.gif',
            4 => '.bmp',
        ),
    'fileManagerActionName' => 'listfile',
    'fileManagerListPath' => '/file/',
    'fileManagerUrlPrefix' => '',
    'fileManagerListSize' => 20,
    'fileManagerAllowFiles' =>
        array (
            0 => '.png',
            1 => '.jpg',
            2 => '.jpeg',
            3 => '.gif',
            4 => '.bmp',
            5 => '.flv',
            6 => '.swf',
            7 => '.mkv',
            8 => '.avi',
            9 => '.rm',
            10 => '.rmvb',
            11 => '.mpeg',
            12 => '.mpg',
            13 => '.ogg',
            14 => '.ogv',
            15 => '.mov',
            16 => '.wmv',
            17 => '.mp4',
            18 => '.webm',
            19 => '.mp3',
            20 => '.wav',
            21 => '.mid',
            22 => '.rar',
            23 => '.zip',
            24 => '.tar',
            25 => '.gz',
            26 => '.7z',
            27 => '.bz2',
            28 => '.cab',
            29 => '.iso',
            30 => '.doc',
            31 => '.docx',
            32 => '.xls',
            33 => '.xlsx',
            34 => '.ppt',
            35 => '.pptx',
            36 => '.pdf',
            37 => '.txt',
            38 => '.md',
            39 => '.xml',
        ),
);


